development:
  host: localhost
  database: longjohn_development

test:
  host: localhost
  database: longjohn_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
